import { createElement } from 'react';
import {
  AlertCircle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowUpDown,
  Ban,
  Bot,
  BookOpen,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Combine,
  Crop,
  Eraser,
  Eye,
  File as FileIcon,
  FileCode,
  FileImage,
  FileMinus,
  FileOutput,
  FilePenLine,
  FileSearch,
  FileText,
  FileX,
  FolderOpen,
  GalleryVertical,
  GitCompare,
  Globe,
  Grid2x2,
  Hash,
  Image as ImageIcon,
  Images,
  Info,
  Languages,
  Layers,
  LayoutGrid,
  Loader2,
  Lock,
  Mail,
  Maximize,
  Minimize2,
  Monitor,
  Moon,
  MoveHorizontal,
  Palette,
  Paperclip,
  PenLine,
  Plug,
  Plus,
  Redo2,
  RefreshCw,
  RotateCw,
  Save,
  Scaling,
  ScanText,
  Scissors,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Stamp,
  Square,
  Sun,
  Table,
  Trash2,
  Undo2,
  Workflow,
  Wrench,
  X,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

/**
 * Explicit icon registry.
 *
 * Tool descriptors name their icon as a string, so something has to map names to
 * components. Importing lucide's full barrel would pull ~1500 icons into the
 * bundle; listing the ones actually used keeps it to what we ship.
 */
const ICONS: Record<string, LucideIcon> = {
  AlertCircle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowUpDown,
  Ban,
  Bot,
  BookOpen,
  Check,
  ChevronDown,
  ChevronRight,
  Combine,
  Crop,
  Eraser,
  File: FileIcon,
  FileCode,
  FileImage,
  FileMinus,
  FileOutput,
  FilePenLine,
  FileSearch,
  FileText,
  FileX,
  FolderOpen,
  GalleryVertical,
  GitCompare,
  Globe,
  Grid2x2,
  Hash,
  Image: ImageIcon,
  Images,
  Info,
  Languages,
  Layers,
  LayoutGrid,
  Loader2,
  Lock,
  Mail,
  Minimize2,
  Monitor,
  Moon,
  Palette,
  Paperclip,
  PenLine,
  Plug,
  Plus,
  RefreshCw,
  RotateCw,
  Save,
  Scaling,
  ScanText,
  Scissors,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Stamp,
  Square,
  Sun,
  Table,
  Trash2,
  Workflow,
  Wrench,
  X,
};

/** Falls back to a generic file icon so a typo in a descriptor never blanks the card. */
export function icon(name: string): LucideIcon {
  return ICONS[name] ?? FileIcon;
}

/**
 * Renders a descriptor's icon by name.
 *
 * Callers use this rather than `const Icon = icon(name)` in their own render:
 * assigning a component to a capitalised local during render is indistinguishable
 * from defining one there, which the React lint rules reject.
 */
export function ToolIcon({ name, ...props }: { name: string } & LucideProps) {
  return createElement(icon(name), props);
}

export {
  AlertCircle,
  ArrowLeft,
  BookOpen,
  Bot,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Eraser,
  Eye,
  FileOutput,
  FilePenLine,
  FileText,
  FolderOpen,
  Languages,
  Loader2,
  Lock,
  Mail,
  Maximize,
  Monitor,
  Moon,
  MoveHorizontal,
  Palette,
  PenLine,
  Plug,
  Plus,
  Redo2,
  RefreshCw,
  RotateCw,
  Save,
  Search,
  Send,
  Settings,
  Stamp,
  Square,
  Sun,
  Trash2,
  Undo2,
  Wrench,
  X,
  Ban,
  ZoomIn,
  ZoomOut,
};
export type { LucideIcon, LucideProps };
